name: clean_arcitechture_edu
description: "A new flutter project for learn clean arctiechrure by weather app."
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  bloc: ^8.1.4
  blurbox: ^0.0.3
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_regular.ttf